### ISSUE TITLE
Request for a pre-trained model with the setting mentioned in your paper

### ISSUE THREAD

**Issue by chen-yingjie** [KyleZheng1997/WCL#1]
Nice work! I've noticed that you provide the results with a hidden dimension of 4096 and output dimension 256 for the projection head. Could you also provide a checkpoint with a hidden dimension of 2048 and output dimension 128 as mentioned in your paper?

Thanks a lot! 
I'm looking forward to hearing from you.

**Comment by mingkai-zheng** [comment]
Sorry, I lost the checkpoint file that I reported in our paper, this is why I retrain the model with a little bit better setting (larger projection head).  
Since we do not change the backbone setting (ResNet50), so the checkpoint we provided should not affect downstream tasks too much. 
Do you have any specific reason to get the checkpoint that we reported in our paper?
