### ISSUE TITLE
can't run torch.distributed.scatter with nccl backend

### ISSUE THREAD

**Issue by pablotalavante** [KyleZheng1997/WCL#6]
Hello, I tried to run your code on a single GPU making some modifications to the code but maintaining the DataPararell code, but I run into a problem [here](https://pytorch.org/docs/1.11/distributed.html)

where I have to run `torch.distributed.scatter(mask1, mask1_list, 0)`. 

You initialize DDP with the `backend=nccl`, but according to the [docs](https://pytorch.org/docs/1.11/distributed.html) this operation is not allowed with this backend.

Do you have any idea how to overcome this? Thank you!

**Comment by mingkai-zheng** [comment]
Sorry, I just realized that I forgot to reply to your question. Since I was using our internal deep-learning library to train the model, so I did not meet this issue. However, to resolve this issue, a simple way is to calculate the 1-nn adjacency matrix on each GPU separately, so you don't have to scatter it from rank0.
